let svg = d3.select("#sketchpad")
  .append("svg")
  .attr("width", 600)
  .attr("height", 600)

svg.append("circle")
  .attr("cx", 150)
  .attr("cy", 200)
  .attr("r", 100)
  .attr("fill", "blue")

svg.append("rect")
  .attr("x", 200)
  .attr("y", 0)
  .attr("width", 250)
  .attr("height", 100)
  .attr("fill", "red")